import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./_components/SideBar";
import TabsGroup from "./_components/TabsGroup";
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          "mx-auto w-full bg-[--background-system-body-base] border-border/40 dark:border-border min-[1800px]:max-w-[1536px] min-[1800px]:border-x flex justify-center items-center overflow-hidden relative  pr-2"
        }
      >
        <SideBar />
        <main
          className="
          md:pl-6 lg:pl-10
          pr-4
          
          overflow-y-auto scrollbar-hidden h-full relative flex min-h-svh flex-1 flex-col peer-data-[variant=floating]:min-h-[calc(100svh-theme(spacing.4))] md:peer-data-[variant=floating]:mb-4 md:peer-data-[state=collapsed]:peer-data-[variant=floating]:ml-2 md:peer-data-[variant=floating]:ml-0  md:peer-data-[variant=floating]:rounded-xl 
          md:peer-data-[variant=floating]:shadow 
          border
          
          group-data-[variant=floating]:border group-data-[variant=floating]:border-sidebar-border
          "
        >
          <TabsGroup />
          {/* <SidebarTrigger /> */}
          <div className="relative py-6 lg:gap-10 lg:py-8 xl:grid xl:grid-cols-[1fr_300px]">
            <ThemeProvider>{children}</ThemeProvider>
            <div className=" text-[6px]">
              <p className="  sticky ">
                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+========++++++
                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@==========+++++
                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+==========+++++
                @@@@@@@@@@@@@@@@@@@%#*+++++++++*+**%===========++++++
                #@@@@@@@@@@@@@%@%%#++++++++++++++*+====++=====+++++++
                *@@@@@@@@%%%%##%*+++++++#%#*+++++*+##+=+=====+===++++
                ++#@@@@%%%%#***+*++++*%##%#*+++++++*%%%%%%#*++==+++++
                ++++++++#%%%##*++++#%#%**#+++++**++*%%#@@@@%%%#++++++
                +++++++++%%@@@@@@%#++*%%#++*++++*++%%%%@@@@@@@%%%#+++
                +++++++++*@@@@#*%@@*++=++**+++++*+++%@@@@@@@@@@@@@@%#
                ++++++++++#%%%%%%@%#++++*++++++*++++@@@@@@@@@@@@@@@@@
                *++++++++*##%#*##%@%*++++**++++++++#@@@@@@@@@@@@@@@@@
                *++++++*%@@##%%##%@@@#*++++**++++++%@@@@@@@@@@@@@@@@@
                **++++%@@@@@%*####%#*#%#**###+++++%@@@@@@@@@@@@@@@@@@
                **++#@@@@@@@@@*##%@@@@%##***+*+++#@@@@@@@@@@@@@@@@@@%
                **+%@@@@@@@@@@@##+*%@@%##*+++*###@@@@@@@@@@@@@@@@@@@@
                *+%@@@@@@@@@@@@@@@**#%*+*+++*##%@@@@@@@@@@@@@@@@@@@@@
                *@@@@@@@@@@@@@@@@@@%###++++**#@@@@@@@@@@@@@@@@@@@@@@@
                @@@@@@@@@@@@@@@@@@@@@@@@%*#@@@@@@@@@@@@@@@@@@@@@@@@@@
              </p>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
